### ISSUE TITLE
Server API Specification

### ISSUE THREAD

**Issue by puregarlic** [puregarlic/socks#1]
This is kinda what I imagine the server API to look like:

```js
const { server } = require('@starburn/socks')

const socketPath = '/tmp/unique.sock'
const events = {
  connect: () => { console.log('Client connected') },
  disconnect: () => { console.log('Client disconnected') },
  hello: (data, socket) => {
    console.log('Received: ', data)
    socket.reply('world', { message: 'world' })
  }
}

server.listen(socketPath, events, () => console.log(`IPC server listening at ${socketPath}`))
```

Although, I'm concerned about what cross-platform support would look like for the socket path. It might be better to hand the server some kind of unique ID that the package can then reliably convert to a path depending on an operating system. Thoughts?

**Comment by starburn** [comment]
Maybe a default path based on an identifier is a good baseline, and then the option to override that path would be good too. I'm looking into the `net` API to see if those events make sense to me.

**Comment by starburn** [comment]
```
const { listen } = require('@starburn/socks')

const handlers = {
  hello: async (payload, socket) => {},
  goodbye: async (_, _, server) => server.close()
}

listen(handlers, options).then(() => console.log('listening'))
```

**Comment by puregarlic** [comment]
This looks perfect.
