### ISSUE TITLE
Convert Actions to HCL

### ISSUE THREAD

**Issue by puregarlic** [puregarlic/socks#4]
This repository doesn't have support for YAML GitHub Actions yet. The current workflows need to be converted back to HCL so we have a working CI system in the meantime; luckily, we can just re-apply our commit which adds the YAML workflow files when the time comes.

**Comment by starburn** [comment]
The version field seems to produce deprecation warnings now.

**Comment by puregarlic** [comment]
I'm going to close this issue and open another issue for that warning, since we have YAML support now.
